server:
  port: 83
spring:
  application:
    name: nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 106.53.74.231:80

management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  http: http://nacos-provider
