server:
  port: 9002
spring:
  application:
    name: nacos-provider

  cloud:
    nacos:
      discovery:
        server-addr: 106.53.74.231:80

management:
  endpoints:
    web:
      exposure:
        include: '*'
