server:
  port: 8882
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定 rabbitmq 的服务信息
        defaultRabbit: #表示定义的名称 用于于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关的环境配置1
            spring:
              rabbitmq:
                host: 192.168.126.138
                port: 5672
                username: leyue
                password: leyue
                virtual-host: /leyue
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称  这是消费者
          destination: yangtaoExchange  #表示要使用的Exchange名称定义
          content-type: application/json  #设置消息类型，本次为json 文本则设置为 text/plain
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: taogegeA

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: send-8802.com
    prefer-ip-address: true
